/**
 * Flashcard types for Zustand store
 *
 * Pattern: Matches sparks/types.ts - defines cache row type for store usage
 */

// Re-export from database types (generated by Supabase CLI)
import type { Database } from '@/types/database'

export type FlashcardCacheRow = Database['public']['Tables']['flashcards_cache']['Row']
export type PromptTemplate = Database['public']['Tables']['prompt_templates']['Row']
export type Deck = Database['public']['Tables']['decks']['Row'] & {
  flashcard_count: number
  due_count: number
}
