-- Disable RLS for development
-- Re-enable when moving to production with:
-- ALTER TABLE table_name ENABLE ROW LEVEL SECURITY;

ALTER TABLE documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE chunks DISABLE ROW LEVEL SECURITY;
ALTER TABLE entities DISABLE ROW LEVEL SECURITY;
ALTER TABLE components DISABLE ROW LEVEL SECURITY;
ALTER TABLE connections DISABLE ROW LEVEL SECURITY;
ALTER TABLE decks DISABLE ROW LEVEL SECURITY;
ALTER TABLE entity_decks DISABLE ROW LEVEL SECURITY;
ALTER TABLE study_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE review_log DISABLE ROW LEVEL SECURITY;

-- Add comments for future reference
COMMENT ON TABLE documents IS 'RLS ready - enable with: ALTER TABLE documents ENABLE ROW LEVEL SECURITY';
COMMENT ON TABLE chunks IS 'RLS ready - enable with: ALTER TABLE chunks ENABLE ROW LEVEL SECURITY';
COMMENT ON TABLE entities IS 'RLS ready - enable with: ALTER TABLE entities ENABLE ROW LEVEL SECURITY';
COMMENT ON TABLE components IS 'RLS ready - enable with: ALTER TABLE components ENABLE ROW LEVEL SECURITY';